version: "3.9"
services:
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  order:
    build: ./order
    container_name: ecomm-order
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - "3003:3003"
    depends_on:
      - mysql
  mongodb:
    container_name: mongo-ecomm
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - VOL1:/data/db
  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=finance
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - volmysql:/var/lib/mysql

volumes:
  volmysql: 
    driver:  local
  VOL1: 