version: "3.9"
services:
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - ${PRODUCT_PORT}:${PRODUCT_PORT}
    depends_on:
      - mongodb
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    depends_on:
      - mongodb
      - redis
  order:
    build: ./order
    container_name: ecomm-order
    ports:
      - ${ORDER_PORT}:${ORDER_PORT}
    depends_on:
      - mongodb
  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - ${FINANCE_PORT}:${FINANCE_PORT}
    depends_on:
      - mysql
  gateway:
    build: ./gateway
    container_name: ecomm-gateway
    ports: 
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - product
      - account
      - order
      - finance
  mongodb:
    container_name: mongo-ecomm
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - VOL1:/data/db
  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_BD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - volmysql:/var/lib/mysql
  redis:
    container_name: redis-ecomm
    image: redis
    restart: always
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
    - redis_data:/data
volumes:
  volmysql: 
    driver:  local
  VOL1: 
  redis_data: