name: Ecomm

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - ${{ MONGO_PORT }}:${{ MONGO_PORT}}
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ MONGO_PASSWORD }}

      mysql:
        image: mysql
        ports:
          - ${{ MYSQL_PORT }}:${{ MYSQL_PORT }}
        env:
          MYSQL_ROOT_PASSWORD: ${{ MYSQL_PASSWORD }}
      redis:
        image: redis
        ports:
          - ${{ REDIS_PORT }}:${{ REDIS_PORT }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_CHAVE_JWT: ${{ secrets.CHAVE_JWT }}
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_PRODUCT_PORT: ${{ secrets.PRODUCT_PORT }}
          envkey_ACCOUNT_PORT: ${{ secrets.ACCOUNT_PORT }}
          envkey_ORDER_PORT: ${{ secrets.ORDER_PORT }}
          envkey_FINANCE_PORT: ${{ secrets.FINANCE_PORT }}
          envkey_GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}
          envkey_MONGO_PORT: ${{ secrets.MONGO_PORT }}
          envkey_MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          envkey_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          envkey_MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          envkey_MYSQL_BD: ${{ secrets.MYSQL_BD }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MONGO_USERNAME }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          file_name: .env
          fail_on_empty: true

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "5.0"

      - name: Install dependencies
        run: |
          cd account && npm install
          cd ../finance && npm install
          cd ../gateway && npm install
          cd ../order && npm install
          cd ../product && npm install

      - name: Eslint checkout
        run: |
          cd account && npm run lint
          cd ../finance && npm run lint
          cd ../gateway && npm run lint
          cd ../order && npm run lint
          cd ../product && npm run lint

      - name: Run jest/supertest checks
        run: |
          cd account && npm test
          cd ../finance && npm test
          cd ../account && npm test
          cd ../order && npm test
          cd ../product && npm test

      - name: Stop services
        run: docker-compose down

    
